HIP_ACO smaller SchedInstruction & flattened arrays
JoshHuttonCode/OptSched pull request #9
Opened 2023-01-11 01:08 UTC by balinck

Summary of changes:

- Batches uses_ and defs_ for use on the device to replace the static 16K allocation per SchedInstruction.
- Several 2D arrays containing per-thread data are now 1D arrays where different sections are accessed by global thread ID.

2023-01-12 00:39 UTC, JoshHuttonCode requested changes

2023-01-12 00:39 UTC, JoshHuttonCode commented on lib/Scheduler/gen_sched.hip.cpp
> +  //assert(dev_rsrvSlots_[GLOBALTID*issuRate] != NULL);
Remove this comment if it is no longer needed.

2023-01-12 00:39 UTC, JoshHuttonCode commented on include/opt-sched/Scheduler/bb_spill.h
> +#endif
Change this to use the same numThreads value as elsewhere in the code.

2023-01-12 22:05 UTC, balinck commented
Made requested changes. Also cleaned up some temporary host arrays we weren't previously.

2023-01-13 00:40 UTC, JoshHuttonCode approved these changes

2023-01-13 00:51 UTC, merged